### ISSUE TITLE
Umbrella: Responsive design for Form Runner

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1181]
Form Runner must run great on phones and tablets out of the box.
- [x] initial detail page support
  - [x] consider pull request #2146
  - [x] initial responsive CSS with eacb19081777d28d6e1606399e8c05fc36a01ccb and following commits, enabled with and 8b3b02afb4acf7a54e63617a81cc31bb70541ffd
- [x] consider #70 and #1670
  - RESOLUTION: not essential for responsive
- [ ] make Summary page responsive #2703
- [ ] make Home page responsive #2704

**Comment by ebruchez** [comment]
We discussed that we might not need to do #1670 first.

**Comment by ebruchez** [comment]
The first big step is that we now have responsive CSS for the Form Runner detail page. This will be in 4.10. Removing 4.10 milestone for the umbrella issue.
