### ISSUE TITLE
Dynamic labels, hints, and help

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1342]
Use case: "Is your name Alise?" where "Alise" comes from other field.

See Tweet: https://twitter.com/BankJovita/status/392280786512015360

This would be a very good feature. Should use AVT-like syntax and/or formatter syntax. Formatting string in label resource. Would write:

```
Is your name {$first-name}?
```

Would require this to be supported at XForms engine level somehow?

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11908529/messages/59292625) for dynamic error messages. Use case: "Value must be less than {$control}".

**Comment by acspike** [comment]
Dynamic labels would be very useful. Users regularly ask for this. Could it be possible to include the Form title? Occasionally have two classes of form fillers with very nearly the same form. It is easy to conditionalize fields and sections, but the title needs to be inclusive of both categories at this time and users would prefer to conditionalize it.

**Comment by ebruchez** [comment]
I think that if we do it for labels we could do it for the title too.

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11908529/messages/62357767#comment_466851277) for these examples:

```
File size must be less than {maxfilesize} MB.
File format is not allowed, allowed file formats are {fileformats}
```

And also for considering automatically-generated hints.

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/Section-title-td4661995.html)

**Comment by ebruchez** [comment]
What would it take to implement this?

Right now, labels and the likes are static and point directly to resources in `fr-form-resources`. A Dynamic label must also be stored in `fr-form-resources` but must be interpreted through a function (tentatively, the existing `xxf:format-message()`).

`File size must be less than {maxfilesize} MB.` could be translated by Form Builder to:

```xml
<xf:label
    ref="
        xxf:format-message(
            xxf:r('control-1.label'),
            (fr:control-value('maxfilesize'))
        )
    "/>
```

where the resource stored in `fr-form-resources` might look like:

    File size must be less than {0} MB.

So this would require:

- [ ] Form Builder: option to specify that an LHHA is a template
    - this raises a UI question as we already have an option to specify that an LHH is in HTML format
    - maybe this could move to Control Settings?
- [ ] Form Builder: parse, validate and serialize templates based on what the user types
    - or could we make that more explicit in an editor so we generate `xxf:format-message()` more directly?
- [ ] `fr:control-value()` function (see #2910)
    - we probably need this as variables don't resolve in the view
- [ ] check that `xxf:format-message()` dependencies work (PathMap)

**Comment by ebruchez** [comment]
After discussion with @avernet, thinking that there are options to handle the template:

- XPath value templates
- Java message format templates
- maybe others (just using `$foo` in the string as in Scala string interpolation?)

Since we support internationalization, we need to ensure that things are consistent

- the parameters to the template should be fixed and shared between languages
- on the other hand a template in a given language can omit some or all of the parameters

So it makes sense to have the ability to specify parameters separately in a list, which probably calls for doing this in Control Settings (and Section Settings, and Form Settings if we handle the title).

**Comment by ebruchez** [comment]
Labels and alerts are important for users so we need to make sure we cover those at least.

**Comment by ebruchez** [comment]
We discussed a possible format in #2427 and #2428 based on Java message format templates.

**Comment by ebruchez** [comment]
Moved comment above to #3078 for defining a template format.

**Comment by ebruchez** [comment]
Here is an initial mockup of the label/hint configuration.

![lh](https://cloud.githubusercontent.com/assets/105769/22521361/a47dae7e-e86c-11e6-8b07-a7a3d57eedf0.jpg)

We probably do not need templates for help.

However we do need them for alerts, which are currently in the "Validations and Alerts" tab, which is already fairly crowded:

![alerts](https://cloud.githubusercontent.com/assets/105769/22521480/f7e8d80e-e86c-11e6-9786-fe6610bc30ac.png)

So how can we handle alerts?

**Comment by ebruchez** [comment]
For alerts, I see 3 possibilities:

- make the dialog wider (might not be reasonably possible)
- open an overlay to setup an alert template (with a button/link)
- move alert messages to the new "Label/Hint" tab
  - all alert messages, static or not, would be editable there
  - in the "Constraints and Alerts" tab, you would see
    - the label as is now if static
    - the template only if dynamic, with an "edit" link to go to the "Label, Hints and Alerts" tab

There is a consistency and visual benefit of grouping LHA in a single tab.

You wouldn't be able to add alerts independently in the "Label, Hints and Alerts" tab. Those would be created from the "Constraints and Alerts" tab as you add constraints. Would this be confusing?

**Comment by ebruchez** [comment]
Current thinking for alerts: try to place the template parameters below the current field for the alert message. Mockup:

![alerts](https://cloud.githubusercontent.com/assets/105769/22528054/7a184224-e886-11e6-9e2d-b93391b102c1.jpg)

**Comment by avernet** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/159f05cf6604d927)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/15cc1a9c58c37fd5) for dynamic section titles

**Comment by ebruchez** [comment]
Another possibility is to expand `xxf:r()`:

```xml
<xf:label
    ref="
        xxf:r(
            'control-1.label',
            (
                fr:control-value('maxfilesize')
            )
        )
    "/>

```

**Comment by ebruchez** [comment]
Next steps:

- [ ] implement modified `xxf:r()`: if parameters are passed, fill them in
- [ ] modify Form Builder to read/write resources as `xxf:r('control-1.label')` instead of `$form-resources/control-1/label`
- [ ] TODO

**Comment by ebruchez** [comment]
One issue with the following is that if, in the 3rd parameter, a member of the sequence returns 0 or more than 1 items, then the result will be unexpected:

```xpath
xxf:r(
    'control-1.label',
    'fr-form-resources',
    (
        fr:control-value('maxfilesize'),
        ...
    )
)
```

Can we, instead, have a "varargs"-style function?


```xpath
xxf:r(
    'control-1.label',
    'fr-form-resources',
    fr:control-value('maxfilesize'),
    ...
)
```

This way, we can ensure that we know how to map each template parameter.

Ideally, we could pass a map, so we could even have named parameters:

```xpath
xxf:r(
    'control-1.label',
    'fr-form-resources',
    map {
        "maxfilesize": fr:control-value('maxfilesize'),
        ...
    },
    ...
)
```

But we don't have support for that yet.

**Comment by ebruchez** [comment]
Form Builder will have to parse the `xxf:r()` expression to extract the template parameters. Can the XPath parser return the textual position, in the source of the XPath expression, of each function parameter?

**Comment by ebruchez** [comment]
We might use a new `fr:r()` function for this, as it is, after all, a Form Runner-specific function.

Another suggestion is to use hashmaps. Since XPath 2.0, which we use, doesn't support the native map syntax, we could implement the map functions from XPath 3.1 for now. We would need:

- `map:entry()` to create the first map
- `map.put()` or `map:merge()` to build the resulting map

This would allow us to use named parameters.

Example:

```xpath
map:merge(
    map:entry('name',        fr:control-value('name')),
    map:entry('maxfilesize', fr:control-value('maxfilesize')),
    map:entry('lang',        fr:lang()
)

```

Or:

```xpath

map:put(
    map:put(
        map:entry(
            'name',
            fr:control-value('name')
        ),
        'maxfilesize',
        fr:control-value('maxfilesize')
    ),
    'lang',
    fr:lang()
)    

```


The benefit of the first approach is that it is more readable compared to the nesting of the second approach.

**Comment by ebruchez** [comment]
Preference for the first approach.

One issue then is to parse Java templates if we use "by name" parameters rather than "by position". For a start, we could just use as superset of a subset of `MessageFormat`. For example:

```
Hi {$name}, you have {$count} file(s).
```

And we can defer supporting more advanced formatting, including choices.

**Comment by avernet** [comment]
I see the rational for `{$count}`, but it rubs me the wrong way, because it is the reverse of `${count}`, which is what is done in Scala or, maybe more importantly, in the [ES2015 template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by ebruchez** [comment]
The thing is in JavaScript and Scala, you refer to variables with their identifier, so `count`. But in XPath, you use the `$` sign. I don't know if there is much sense to make things compatible with JavaScript or Scala given that the rest of the syntax will be different. For example, will you write this:

```
${$count}
```

**Comment by ebruchez** [comment]
To be fair, the Java syntax is `{0, ...}` so we could do `{count, ...}` and still be able to parse things.

**Comment by ebruchez** [comment]
Regarding expression parsing, we still have an issue because our version of Saxon doesn't store column or range information for an expression: only the line number is stored in an expression.

Saxon 9.8 supports storing column numbers. Could that be enough? If so, we could use Saxon 8's XPath parser to extract information, pending #976 which is more work.

**Comment by ebruchez** [comment]
Confirming that `toString` on expressions with Saxon 9.1 doesn't round-trip even with plain parsing.  For example:

```xpath
xxf:r('foo.bar', 'fr-form-resources', map:entry('key1', a / b))
```

produces:

```
`Some(xxf:r("foo.bar", "fr-form-resources", map:entry("key1", SlashExpression(child::element(a, xs:anyType), child::element(b, xs:anyType)))))`
```

**Comment by ebruchez** [comment]
Saxon 9.8 doesn't seem to help much with column numbers. With `a / b`, for example, the "slash" expression seems to be positioned at column 3. This is the case even if we don't call `simplify()` on the resulting `Expression`.

`toString` results are improved, for example:

```
("foo.bar", "fr-form-resources"), Q{http://www.w3.org/2005/xpath-functions/map}entry("key1", (((.) treat as node())/child::element(Q{}a))/child::element(Q{}b))
```

But still, it is not usable to roundtrip expressions.

**Comment by ebruchez** [comment]
In the meanwhile, we could support only control values, as was initially planned. So we would have expressions of the shape:

```xpath
fr:r(
    'foo.bar',
    map:merge(
        (
            map:entry('name',        fr:control-value('name')),
            map:entry('maxfilesize', fr:control-value('maxfilesize'))
        )
    )
)
```

**Comment by ebruchez** [comment]
We now show label and hint in the Control Settings dialog (e9bf0846fe1e3a1b2baa19bcee87be9521e8d269).

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966555/messages/659844742#__recording_794292693) for getting labels from a dataset.

**Comment by ebruchez** [comment]
Regarding the use of datasets, the user would like to write expressions like `fr:dataset('my-dataset')/a[2]/b`. So we need to know where the expression starts and end in:

```xpath
fr:r(
    'foo.bar',
    map:merge(
        (
            map:entry('quantity', fr:dataset('my-dataset')/a[2]/b)
        )
    )
)
```

Now we don't need to roundtrip, just to know where the expressions start and end, but that too might not be obtainable from Saxon 9.8.

**Comment by ebruchez** [comment]
Confirming that Saxon is hopeless to provide the location of subexpressions or function parameter arguments.

**Comment by ebruchez** [comment]
Since parsing XPath expressions doesn't work without improving the Saxon parser, another solution is for Form Builder to represent LHHA templates using XML:

```xml
<xf:input bind="thingy-control">
  <xf:label ref="$form-resources/thingy/label">
    <fr:param name="quantity" value="fr:dataset('my-dataset')/a[2]/b"/>
    <fr:param value="name" vaue="fr:control-value('name')"/>
  </xf:label>
<xf:input>
```

or:

```xml
<xf:input bind="thingy-control">
  <xf:label ref="$form-resources/thingy/label">
    <fr:param name="quantity" expr="fr:dataset('my-dataset')/a[2]/b"/>
    <fr:param value="name" control-value="name"/>
  </xf:label>
<xf:input>
```

The presence of `<fr:param>` child element would imply that the resource is a template. There is no need to name the resource as it must match that of the control.

At runtime and/or publishing time, but not a design time, the nested `<fr:param>` would translate to a `ref` attribute on `<xf:label>` which would contain the entire `xf:r()` or `fr:r()` expression.

We can decide to leave the standard `ref` on `<xf:label>`, knowing that it would be overridden by the translation. This would allow, at design time, the edit the template directly. We certainly don't want the template to be evaluated with its parameters at design-time.

**Comment by ebruchez** [comment]
Updated next steps:

- [ ] finish implementing modified `xxf:r()` to support template (#3297)
- [ ] Form Builder UI changes
  - [ ] backend to read/write LHA with template
  - [ ] checkbox to enable template
  - [ ] support expression
  - [ ] support control value: `fr:control-value('maxfilesize')`
- [ ] generate `xxf:r()` from `<fr:param>` representation
- [x] implement #1328 to support indexes
- [x] implement #3293 "Add simple XPath 3.1 Map functions"
- [ ] P2: check whether #2426 is relevant

**Comment by ebruchez** [comment]
To facilitate switching, we could do:

```xml
<xf:input bind="thingy-control">
  <xf:label ref="$form-resources/thingy/label">
    <fr:param type="expr">
      <fr:expr>fr:dataset('my-dataset')/a[2]/b</fr:expr>
    </fr:param>
    <fr:param type="control-value">
      <fr:control-name>name</fr:control-name>
    </fr:param
  </xf:label>
<xf:input>
```

But we should ideally match the format we use in other places, like:

```xml
<json type="array">
    <_ type="ExpressionParam">
        <expr>...</expr>
    </_>
    <_ type="ControlValueParam">
        <controlName>...</controlName>
    </_>
</json>
```

That is not as nice a format but is it ok?

**Comment by ebruchez** [comment]
For alerts, we might have to put them out of the main Validations and Alerts tab. An Alerts tab could list all alerts in the same order as in the Validations tab. and so the linking would be simple.

**Comment by ebruchez** [comment]
When using a control value, we might want to format the value if it is a typed value. For example a date should not show as ISO. For this to happen, we want the value to have a type, which implies that the value returned by `fr:control-value()` (or `fr:control-typed-value()`) must be typed. If the value is not compatible with the type, it should return an empty sequence.

The way `xf:output` formats values by default should probably be used by `xxf:r()`, which means using properties like:

```xml
<property as="xs:string"  name="oxf.xforms.format.output.date">
    if (. castable as xs:date) then
        format-date(xs:date(.), '[FNn] [MNn] [D], [Y]', xxf:lang(), (), ())
    else
        .
</property>
```

**Comment by ebruchez** [comment]
By default, when saying we want the "value of a control", we should:

- use the typed value and therefore call `fr:control-typed-value()`
  - this means that if the value is not per the type, the value won't show
- use the *first* value available
  - `fr:control-typed-value()` can return all of them
  - we take the first one only
  - later we could have options: "use first" or "join all" ("follow repeat indexes" is not very useful)
- the value is formatted by `xxf:r()` like `xf:output` does for typed values

**Comment by ebruchez** [comment]
We must also implement dynamic labels, hints and help for sections, as customer reminded us.

**Comment by ebruchez** [comment]
How much work is needed to implement dynamic error messages? If reasonable include in 2018.1, otherwise enter separate issue and postpone that part.

**Comment by ebruchez** [comment]
For dynamic alerts, we should fix the syntax for #1328.

**Comment by ebruchez** [comment]
- [ ] create separate bug for dynamic alerts

**Comment by ebruchez** [comment]
Entered #3628 for dynamic alerts.

**Comment by ebruchez** [comment]
Moving remaining tasks here:

- [ ] BUG: maybe `fr:error-summary`: errors show funny with repeats
- [ ] finish implementing modified `xxf:r()` to support template (#3297)
- [ ] send build to customer with at least LHH support
- [ ] the value is formatted by `xxf:r()` like `xf:output` does for typed values
- [ ] P2
  - [ ] support item labels for selection controls
  - [ ] check whether #2426 is relevant

**Comment by ebruchez** [comment]
Now documented:

- [Template syntax](https://doc.orbeon.com/form-builder/advanced/template-syntax)
- [ Dynamic labels, hints and help messages](https://doc.orbeon.com/form-builder/form-editor/control-settings#dynamic-labels-hints-and-help-messages)
- [Dynamic email subject and body](https://doc.orbeon.com/form-builder/form-editor/email-settings#dynamic-email-subject-and-body)
