### ISSUE TITLE
Umbrella: Modernize and modularize the build

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1585]
For sanity and future-proofing, we need to take steps to break dependencies and modularize the build.

Subprojects:
- [x] Move build to sbt, phase 1 #2232
- [x] Move build to sbt, phase 2 #2805
- [x] Automatically produce CSS from LESS #351

Potential modules:
- [ ] misc utilities
- [ ] XML utilities
- [ ] resource manager
- [ ] XPL pipeline engine
- [ ] XML processors
- [ ] legacy XML processors (see #1613)
- [x] dom implementation (see #2165)
- [x] legacy XUpdate processor (see #2164)
- [ ] XForms engine
- [x] Form Runner
- [x] Form Builder

The new build system would probably use sbt.

Useful tools:
- http://www.jetbrains.com/idea/features/dependency_analysis.html
- https://github.com/sbt/sbt-web
- http://www.webjars.org/

**Comment by ebruchez** [comment]
For reference, the Scala project itself just got an [experimental sbt build](https://github.com/scala/scala/pull/4455).

**Comment by ebruchez** [comment]
Recently created `formBuilder` and `formRunner`modules, see f28d8d81df29dcd160e01ca01c44622ab5c8af19 and c71b98a35bc28d3b15d1ac7850a3e53110fd1730 and some of the subsequent commits.

**Comment by ebruchez** [comment]
Now moved XBL components to the `formRunner` project.

**Comment by ebruchez** [comment]
Next step is to move Java/Scala files to the `xforms` module. Issues:

- `scaxon.XML.scala` depends on XForms code (`XFormsInsertAction`, `XFormsInstance`)
  - split appropriately
  - maybe low-level operations on nodes, like `insert`, can be moved out of `xforms`
- `PipelineFunctionLibrary.scala` depends on XForms functions
  - functions depend on `XFormsFunction`
  - `RequestFunction` depends on `XFormsContainingDocument`

**Comment by ebruchez** [comment]
Moved `xforms` module work to #3292.
