### ISSUE TITLE
Doc improvement project

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1592]
## Currently

Our doc needs some love:
- it is in two places
  - [wiki.orbeon.com](wiki.orbeon.com/forms/) (Google Sites)
  - [github wiki](https://github.com/orbeon/orbeon-forms/wiki)
- it is hard to figure out
  - what is the latest and greatest
  - what is legacy
  - an overview of the doc
  - where exactly to get started
- it doesn't look good, especially on the wiki
## Priorities
1. **Starting point:** It must be clear to users (current and prospective) where the doc is and how to get started.
2. **Prioritization:**: We must clearly show the topics most likely to be of interest to most users. For example, they should not be confused by XForms or XPL doc if what they want to do is learned how to setup Form Builder.
3. **Quality**: The doc must be consistent, easy to read and navigate, and have no broken links.
4. **Design**: The doc must look reasonably good.
5. **Maintenance**: The doc must be relatively easy to maintain and update.
## Implications
- Migrate the documentation from the old wiki to a single location.
- Old and obsolete doc is removed (or clearly placed in an "attic").
- Use Markdown.
## Later
- Use a site/doc generator from the Markdown.
- Version doc per Orbeon Forms release.
  - "Orbeon Forms 4.13" (say): contains only latest doc (remove SINCE markers)
  - "Older Orbeon Forms versions": contains "current" doc (including SINCE markers)
  - _NOTE: This raises the question of updating older doc when fixes are made._
- Maybe: add Disqus comments do all doc pages for feedback and discussion. Is this a good idea? Do other sites do it?
## Topics to cover
1. Overview/install ([current starting point](https://github.com/orbeon/orbeon-forms/wiki/Installation))
2. Orbeon Forms use cases (#228) (can be on www.orbeon.com)
3. FB/FR user manuals
4. Form Builder and Form Runner integration (#2019)
5. Then only XForms and other details
## Pages to migrate
- [x] [Form Builder User Guide](http://wiki.orbeon.com/forms/doc/user-guide/form-builder-user-guide) (#219)
  - [x] base doc (split if needed)
  - [x] [Database Services](http://wiki.orbeon.com/forms/doc/user-guide/form-builder-user-guide/database-services)
  - [x] [Component Metadata](http://wiki.orbeon.com/forms/doc/user-guide/form-builder-user-guide/toolbox-component-metadata)
  - [x] decide what to do with [French version of guide](http://wiki.orbeon.com/forms/doc/user-guide/orbeon-forms-builder-guide-utilisateur)
- [x] [Guide to Using and Writing XBL Components](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components-guide)
- [x] [Configuring a Form Runner eXist database](http://wiki.orbeon.com/forms/doc/developer-guide/exist-configuration)
- [x] XBL components exposed in Form Builder
  - [x] [Currency](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/currency)
  - [x] [Data-bound Select1](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/databound-select1)
  - [x] [Image annotation](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/image-annotation)
  - [x] [Number](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/number)
  - [x] [TinyMCE Editor](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/tinymce)
  - [x] [US State](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/us-state)
- [x] Other XBL components in use
  - [x] [Alert dialog](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/alert-dialog)
  - [x] [Captcha components: reCAPTCHA and SimpleCaptcha](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/recaptcha)
  - [x] [Error Summary Component](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/error-summary-component)
  - [x] [Source Code Editor](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/source-code-editor)
  - [x] [XForms Inspector](http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/xforms-inspector)
- [ ] Other Form Runner pages
  - [x] [Dates and times in Orbeon Forms data](http://wiki.orbeon.com/forms/doc/developer-guide/dates-and-times-in-orbeon-forms-data)
  - [x] [Auditing](http://wiki.orbeon.com/forms/doc/developer-guide/form-runner/auditing)
  - [x] [Importing Data to Form Runner](http://wiki.orbeon.com/forms/doc/developer-guide/form-runner/importing-data)
  - [x] [Monitoring HTTP Requests](http://wiki.orbeon.com/forms/doc/developer-guide/admin/monitoring-http-requests)
  - [x] [Overriding or adding resources without changing Orbeon Forms](http://wiki.orbeon.com/forms/doc/developer-guide/admin/overriding-adding-resources)
  - [ ] [Performance, Tuning, and Sizing](http://wiki.orbeon.com/forms/doc/developer-guide/admin/performance-tuning)
  - [x] [Security and XSS](http://wiki.orbeon.com/forms/doc/developer-guide/admin/security-xss)
  - [ ] Merge "Performance, Tuning, and Sizing" and "XForms - Performance Settings" pages #323
  - [ ] [Form Runner - URIs Format](http://wiki.orbeon.com/forms/doc/contributor-guide/form-runner-uris)
- [x] XForms
  - [x] [XForms - XPath Function Library](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-xpath-functions)
  - [x] [XForms - Logging](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-logging)
  - [x] [Orbeon Forms XForms Tutorial](http://wiki.orbeon.com/forms/doc/developer-guide/orbeon-forms-xforms-tutorial)
  - [x] [Delayed Events](http://wiki.orbeon.com/forms/doc/developer-guide/delayed-events)
- [ ] Core platform
  - [x] [Resource Managers](http://wiki.orbeon.com/forms/doc/developer-guide/resource-managers)
  - [ ] [Packaging and Deployment](http://wiki.orbeon.com/forms/doc/developer-guide/packaging-and-deployment)
  - [x] [Page Flow Controller](http://wiki.orbeon.com/forms/doc/developer-guide/page-flow-controller)
  - [ ] [Page Flow Epilogue](http://wiki.orbeon.com/forms/doc/developer-guide/page-flow-epilogue)
  - [ ] [XML Namespaces](http://wiki.orbeon.com/forms/doc/developer-guide/xml-namespaces)
  - [ ] [Handling XML Comments](http://wiki.orbeon.com/forms/doc/developer-guide/handling-xml-comments)
  - [ ] [Context and Session Listeners](http://wiki.orbeon.com/forms/doc/developer-guide/context-and-session-listeners)
- [ ] Other
  - [x] [Persistence API](http://wiki.orbeon.com/forms/doc/developer-guide/form-runner/persistence-api): this used a lot
  - [ ] [Third-Party Java Libraries](http://wiki.orbeon.com/forms/doc/contributor-guide/third-party-java-libraries)
  - [ ] [Third-Party JavaScript and CSS Libraries](http://wiki.orbeon.com/forms/doc/contributor-guide/libraries)
  - [ ] [Profiling with YourKit](http://wiki.orbeon.com/forms/doc/contributor-guide/profiling-yourkit)
  - [ ] [XForms - Development Environment](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-development-environment)
- [ ] XPL
  - [ ] [XML Pipeline Language (XPL)](http://wiki.orbeon.com/forms/doc/developer-guide/xml-pipeline-language-xpl)
  - [ ] [API - Pipeline Engine API](http://wiki.orbeon.com/forms/doc/developer-guide/api-pipeline-engine-api)
  - [ ] [API - XPL Processor API](http://wiki.orbeon.com/forms/doc/developer-guide/api-xpl-processor-api)
  - [ ] [Authentication](http://wiki.orbeon.com/forms/doc/developer-guide/authentication)
- [ ] Maybe
  - [ ] [Orbeon Forms 4 release notes](http://wiki.orbeon.com/forms/doc/developer-guide/release-notes/40)
- [ ] Controls
  - [x] [Dialog](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-controls/dialog-control)
  - [ ] [Group](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-controls/group-control)
  - [x] [Input](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-controls/input-control)
  - [x] [Output](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-controls/output-control)
  - [ ] [Secret](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-controls/secret-control)
  - [ ] [Selection](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-controls/selection-controls)
  - [x] [Trigger](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-controls/trigger-control)
  - [x] [Upload](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-controls/upload-control)
- [ ] XPL
  - [ ] [XPL - Command Line Applications](http://wiki.orbeon.com/forms/doc/developer-guide/xpl-command-line-applications)
  - [x] [XPL - Non-XML Documents](http://wiki.orbeon.com/forms/doc/developer-guide/xpl-non-xml-documents)
- [ ] XForms
  - [x] [XForms - Advanced Submissions](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-advanced-submissions)
  - [x] [XForms - Asynchronous Submissions](http://wiki.orbeon.com/forms/doc/developer-guide/asynchronous-submissions)
  - [ ] [XForms - Attribute Value Templates](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-attribute-value-templates)
  - [x] [XForms - Actions](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-actions)
  - [x] [script and action actions for scripting](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-actions/actions-script-action)
  - [x] [XForms - Events](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-events)
  - [ ] [XForms - Extensions](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-extensions)
  - [x] [XForms - Focus](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-focus)
  - [x] [XForms - JavaScript and CSS Resources](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-javascript-css-resources)
  - [x] ~~[XForms - Noscript (Accessible) Mode Guide](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-noscript-mode-guide)~~
  - [ ] [XForms - Other Extensions](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-other-extensions)
  - [ ] [XForms - Performance Settings](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-performance-settings)
  - [x] [XForms - Refresh Events](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-refresh-events)
  - [x] [XForms - Using the Orbeon Forms XForms Engine with Java Applications](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-with-java-applications)
  - [x] [XForms - Variables](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-variables)
  - [x] [XForms - XForms Inspector](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-xforms-inspector)
  - [x] [XForms - XPath 2.0 Support](http://wiki.orbeon.com/forms/doc/developer-guide/xpath-2-0-support)
  - [x] [XForms - XPath Analysis](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-xpath-analysis)
- [ ] Development
  - [ ] [DUP?] [XForms - Development Environment](http://wiki.orbeon.com/forms/doc/developer-guide/xforms-development-environment)
  - [ ] [Code Conventions](http://wiki.orbeon.com/forms/doc/contributor-guide/development-environment/code-conventions)
  - [ ] [JavaScript Development](http://wiki.orbeon.com/forms/doc/contributor-guide/development-environment/javascript-development)
  - [ ] [Orbeon Source Code Repository](http://wiki.orbeon.com/forms/doc/contributor-guide/development-environment/orbeon-source-code-repository)
- [ ] Misc
  - [ ] [Orbeon Form Runner - Programmer and Administrator Guide](http://wiki.orbeon.com/forms/doc/user-guide/form-runner-user-guide)
  - [ ] [Error Page](http://wiki.orbeon.com/forms/doc/developer-guide/error-page-and-error-dialog)
- [ ] Processors
  - [ ] [Processors - Cache Processor](http://wiki.orbeon.com/forms/doc/developer-guide/processors-cache-processor)
  - [ ] [Processors - Converters](http://wiki.orbeon.com/forms/doc/developer-guide/processors-converters)
  - [ ] [Processors - Directory Scanner](http://wiki.orbeon.com/forms/doc/developer-guide/processors-directory-scanner)
  - [ ] [Processors - Email](http://wiki.orbeon.com/forms/doc/developer-guide/processors-email)
  - [ ] [Processors - File Processor](http://wiki.orbeon.com/forms/doc/developer-guide/processors-file-processor)
  - [ ] [Processors - HTTP Serializer](http://wiki.orbeon.com/forms/doc/developer-guide/processors-http-serializer)
  - [ ] [Processors - Java](http://wiki.orbeon.com/forms/doc/developer-guide/processors-java)
  - [ ] [Processors - LDAP](http://wiki.orbeon.com/forms/doc/developer-guide/processors-ldap)
  - [ ] [Processors - Other](http://wiki.orbeon.com/forms/doc/developer-guide/processors-other)
  - [ ] [Processors - Other Generators](http://wiki.orbeon.com/forms/doc/developer-guide/processors-other-generators)
  - [ ] [Processors - Other Serializers](http://wiki.orbeon.com/forms/doc/developer-guide/processors-other-serializers)
  - [ ] [Processors - Pipeline](http://wiki.orbeon.com/forms/doc/developer-guide/processors-pipeline)
  - [ ] [Processors - Request Generator](http://wiki.orbeon.com/forms/doc/developer-guide/processors-request-generator)
  - [ ] [Processors - Scheduler](http://wiki.orbeon.com/forms/doc/developer-guide/processors-scheduler)
  - [ ] [Processors - SQL](http://wiki.orbeon.com/forms/doc/developer-guide/processors-sql)
  - [ ] [Processors - URL Generator](http://wiki.orbeon.com/forms/doc/developer-guide/processors-url-generator)
  - [ ] [Processors - Validation](http://wiki.orbeon.com/forms/doc/developer-guide/processors-validation)
  - [ ] [Processors - XForms Submission](http://wiki.orbeon.com/forms/doc/developer-guide/processors-xforms-submission)
  - [ ] [Processors - XInclude](http://wiki.orbeon.com/forms/doc/developer-guide/processors-xinclude)
  - [ ] [Processors - XSLT and JAXP (TrAX)](http://wiki.orbeon.com/forms/doc/developer-guide/processors-xslt-jaxp)
  - [ ] [Processors - Zip and Unzip](http://wiki.orbeon.com/forms/doc/developer-guide/processors-zip-unzip)
## Examples of docs to look at
- http://slick.typesafe.com/doc/2.0.0/
- [sbt](http://www.scala-sbt.org/0.13/docs/index.html): you can switch the version at the top

**Comment by avernet** [comment]
A first step would be to create "table of content" pages for Form Runner and XForms, and link to those pages from the [wiki home page](https://github.com/orbeon/orbeon-forms/wiki).

**Comment by ebruchez** [comment]
Maybe related: I started a [list of Orbeon Forms Features](https://github.com/orbeon/orbeon-forms/wiki/Orbeon-Forms-Features).

**Comment by acspike** [comment]
A users' perspective: I really appreciate the approach taken by [PostgreSQL](http://www.postgresql.org/docs/9.1/static/tutorial-window.html) and [Django](https://docs.djangoproject.com/en/1.5/) where there is new documentation for each version and multiple versions are visible at once. Much less confusing than seeing each page of docs split for 3.9 and 4.0+ versions.

**Comment by ebruchez** [comment]
Agreed. The 3.9 doc is probably of very little use right now, but for the various 4.x releases it would be nice to have doc in sync. But to get there we must first finish migrating doc from the old Google Sites wiki to Markdown.

**Comment by ebruchez** [comment]
This is still current. We have since migrated some pages on a need basis, but there is a lot of remaining work to do.

**Comment by ebruchez** [comment]
Possibly [gitbook](https://github.com/GitbookIO/gitbook) could be used.

**Comment by ebruchez** [comment]
Update: We have made progress migrating quite a bit of doc recently. Most of the Form Builder / Form Runner documentation we had on the old wiki in particular is now migrated.

**Comment by ebruchez** [comment]
Update: All files converted to Markdown! Now need to move remaining ones to GitBook.

**Comment by ebruchez** [comment]
Also noting this funny page [Programming with XForms](http://wiki.orbeon.com/forms/programming-with-xforms). It covers a few XForms topics, but not the view for example. We should probably just remove it.
