### ISSUE TITLE
Progressively get rid of YUI

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1599]
We now use jQuery, Bootstrap, and other client-side components like TinyMCE. We should be able to retire YUI.

Actions:
- [ ] move to jQuery or plain DOM
  - [ ] DOM manipulation (`YAHOO.util.Dom`) and base utilities (counts of occurrences under `resources-packaged/ops/javascript` as of 2016-03-20)
    - [ ] 33 `YAHOO.util.Dom.addClass`
    - [ ] 30 `YAHOO.util.Dom.removeClass`
    - [ ] 20 `YAHOO.util.Dom.hasClass`
    - [ ] 19 `YAHOO.util.Dom.getElementsByClassName`
    - [ ]  7 `YAHOO.util.Dom.setStyle`
    - [ ]  7 `YAHOO.util.Dom.generateId`
    - [ ]  4 `YAHOO.util.Dom.inDocument`
    - [ ]  4 `YAHOO.util.Dom.getChildren`
    - [ ]  3 `YAHOO.util.Dom.getPreviousSibling`
    - [ ]  3 `YAHOO.util.Dom.getNextSibling`
    - [ ]  3 `YAHOO.util.Dom.getFirstChild`
    - [ ]  3 `YAHOO.util.Dom.getAncestorByClassName`
    - [ ]  2 `YAHOO.util.Dom.insertBefore`
    - [ ]  2 `YAHOO.util.Dom.getViewportHeight`
    - [ ]  1 `YAHOO.util.Dom.insertAfter`
    - [ ]  1 `YAHOO.util.Dom.getViewportWidth`
    - [ ]  1 `YAHOO.util.Dom.getStyle`
    - [x]  1 `YAHOO.util.Dom.getRegion`
    - [ ]  1 `YAHOO.util.Dom.getElementsBy`
    - [ ]  1 `YAHOO.util.Dom.getDocumentScrollTop`
    - [ ]  1 `YAHOO.util.Dom.getDocumentScrollLeft`
  - [ ] more DOM manipulation (`ORBEON.util.Dom`) (counts of occurrences under `resources-packaged/ops/javascript` as of 2016-03-20)
    - [ ] 74 `ORBEON.util.Dom.getAttribute`
    - [ ] 61 `ORBEON.util.Dom.get`
    - [ ] 22 `ORBEON.util.Dom.getChildElementByIndex`
    - [ ] 13 `ORBEON.util.Dom.getStringValue`
    - [ ] 11 `ORBEON.util.Dom.getChildElementByClass`
    - [ ]  8 `ORBEON.util.Dom.getElementByTagName`
    - [ ]  7 `ORBEON.util.Dom.isElement`
    - [ ]  5 `ORBEON.util.Dom.getElementsByName`
    - [ ]  4 `ORBEON.util.Dom.setStringValue`
    - [ ]  2 `ORBEON.util.Dom.stringToDom`
    - [ ]  2 `ORBEON.util.Dom.setAttribute`
    - [x]  2 `ORBEON.util.Dom.nudgeAfterDelay`
    - [ ]  2 `ORBEON.util.Dom.focus`
    - [ ]  2 `ORBEON.util.Dom.blur`
    - [ ]  1 `ORBEON.util.Dom.existsAncestorOrSelf`
    - [x]  1 `ORBEON.util.Dom.ELEMENT_TYPE`
  - [x] some event handling
  - [x] Ajax calls (`YAHOO.util.Connect `)
- [ ] move to Bootstrap
  - [x] dialogs (#2835)
  - [ ] tooltips [2016-06-01: seems we are still using YUI tooltips if `oxf.fr.detail.hints.inline` is set to `false`]
- [ ] keep but move YUI dependencies to the XBL component
  - [ ] `fr:autocomplete`
        - 2019-12-10: We have an Improved autocomplete control (#1433) but `fr:autocomplete` remains for backward compatibility
- [x] later
  - [x] Improved autocomplete control #1433
- [x] replace YUI calendar #2800
    - 2019-12-10: We use another calendar as part of `fr:date` but YUI calendar is still in for backward compatibility.
- [x] remove altogether
  - [x] YUI RTE support
  - [x] ProgressBar

Any other?

**Comment by ebruchez** [comment]
Removed RTE with fix to #2618: see c82604a576f01a487b23b8bb2889d4856aaf359c and 67f7883f9e8d362c01a5a08e75d80b3e3185d8c1.

**Comment by ebruchez** [comment]
Some of the steps above might be outdated. For example:

- we use jQuery less and aim for even less
- for dialogs and tooltips, we have to consider whether we want to depend on Bootstrap

**Comment by ebruchez** [comment]
Uses in xforms.js right now:

```
YAHOO.lang.isBoolean
YAHOO.lang.isNumber
YAHOO.lang.isObject
YAHOO.util.CustomEvent
YAHOO.util.CustomEvent.FLAT)
YAHOO.util.CustomEvent.FLAT),
YAHOO.util.CustomEvent.LIST, true),
YAHOO.util.Dom.getAncestorByClassName
YAHOO.util.Dom.getChildren
YAHOO.util.Dom.getElementsByClassName
YAHOO.util.Dom.getNextSibling
YAHOO.util.Dom.getPreviousSibling
YAHOO.util.Dom.inDocument
YAHOO.util.Event.getTarget
YAHOO.util.Event.throwErrors = true;
YAHOO.util.Subscriber
YAHOO.widget.Tooltip
```

In AjaxServer.js:

```
YAHOO.util.Dom.getFirstChild
YAHOO.util.Dom.insertBefore
YAHOO.util.Dom.inDocument
YAHOO.util.Dom.removeClass
YAHOO.util.Dom.addClass
```

**Comment by avernet** [comment]
We want get rid of YUI in:

- [ ] Widgets: TabView, Autocomplete, Error Panel, Tooltips
- [ ] Custom event system in `xforms.js`
- [x] DOM utility methods in `xforms.js`
- [ ] CSS styling tied to YUI class names

More details:

- Widgets / XBL Components

    | Component        | Files                                                         | YUI Module Used                                                        |
    |------------------|---------------------------------------------------------------|------------------------------------------------------------------------|
    | **TabView**      | `xbl/orbeon/tabview/tabview.xbl`, `tabview.js`                | `YAHOO.widget.TabView`, `YAHOO.util.Dom`                               |
    | **Autocomplete** | `xbl/orbeon/autocomplete/autocomplete.xbl`, `autocomplete.js` | `YAHOO.widget.AutoComplete`, `YAHOO.util.Dom`, `YAHOO.util.DataSource` |
    | **Error Panel**  | `ErrorPanel.scala`                                            | `YAHOO.widget.Panel`, `YAHOO.util.Subscriber`                          |
    | **Tooltips**     | `xforms.js`, `Globals.scala`, `XFormsUI.scala`                | `YAHOO.widget.Tooltip`                                                 |
    
- Event System (`xforms.js`)

    - The main `xforms.js` file uses `YAHOO.util.CustomEvent` for many events: `beforeValueChange`, `valueChange`, `afterValueChange`, `orbeonLoadedEvent`, `errorEvent`, `componentChangedLayoutEvent`, `componentInitialized`, etc.
    - `orbeonLoadedEvent` and `errorEvent` are documented, so we keep those, but provide our own implementation of the methods mentioned in the documentation.
    
-  DOM Utilities (`xforms.js`)

    Uses `YAHOO.util.Dom` methods: `getElementsByClassName()`, `getChildren()`, `getPreviousSibling()`, `getNextSibling()`, `inDocument()`, `getAncestorByClassName()`.

- Scala.js Facades

    - `yui.scala` ,  defines `YUICustomEvent` trait (with a comment referencing issue #1599 for removal)
    - `facades.scala` ,  declares multiple properties typed as `YUICustomEvent`
    - `Constants.scala` ,  `YuiSkinSamClass = "yui-skin-sam"`

- CSS/LESS References

    | File                      | YUI Classes Used                             |
    |---------------------------|----------------------------------------------|
    | `form-runner-dialog.less` | `.yui-panel-container`, `.yui-dialog`        |
    | `autocomplete.less`       | `.yui-ac-content`                            |
    | `grid.less`               | `.yui-button`                                |
    | `tree-select1.less`       | YUI TreeView sprite                          |
    | `xforms.less`             | `.yui-pb`, `.yui-calendar`, `.yui-tt-shadow` |

    - `error-dialog-noscript.xml` ,  uses `yui-panel` class for error dialog markup

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/16915667/messages/9226596396)

**Comment by ebruchez** [comment]
We have only two documented events exposed:

- `orbeonLoadedEvent`
-  `errorEvent`

For these, we can:

- remove the YUI implementation
- keep/re-implement the exposed methods
- deprecate them
- with #7666, we'll have a modern implementation
