### ISSUE TITLE
Umbrella: Improve memory usage and caching of forms

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1606]
This is an umbrella bug. Related bugs:
- [ ] #2013: Session heartbeat doesn't work as intended
- [ ] #1989: Issue with cache eviction from other thread
- [ ] #2014: Heartbeat per form session
- [ ] #1596: Sessions time out sooner than session-timeout setting unpredictably
- [ ] #1990: Expire entries from disk store
- [ ] #1973: Improved XForms document cache sized in bytes 
- [ ] #1572: Make static state cache weaker
- [ ] #1991: There can be more than one copy of the static state in memory
- [ ] #1339: Support XForms inline instance whitespace stripping
- [ ] #1715: Publish should strip whitespace from form definition
- [ ] #2128: XForms: static state must not depend on dom4j
- [ ] #1204: More optimal static representation of forms
- [ ] #1605: Too many duplicate strings
- [ ] #1239: Improve caching to reduce delay between request and XForms processing
- [ ] #1712: For #1143: Complete noscript mode caching changes
- [ ] #1731: Schema mode should use same cacheable form definition
- [ ] #1730: FB: Test mode must not use cache entries
- [ ] #1815: Passivate XFCD state upon FR navigation or asynchronously
- [ ] #1946: Form Runner admin/performance console
- [x] #1681: Caching of form definition is influenced by document id
- [x] #1143: FR: new/edit/view/pdf modes must use same cached form definition
- [x] #1718: Review XForms cache architecture
