### ISSUE TITLE
Consider removing obsolete JAR files from distribution

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1613]
We have lots of JAR files for specific XML processors which haven't been maintained, including:
- [x] `axis_1_2_1-axis.jar` and dependencies
- [x] `jfreechart-1.0.9.jar` (deprecating in 2016.1) (#3026)
- [x] metadata-extractor: unclear
    - 2022-07-25: used by `ImageMetadata`, so keep for now.
- [ ] `exist-dependency-xmldb.jar` (comes with eXist)
  - 2016.1 deprecated XMLDB processors
  - 2016.2 removed XMLDB processors
- [x] `batik-all-1_7.jar` and dependencies (+1 to keep from 2014 from @evlist below, not sure if still relevant) (#3365)
- [x] `fop-1_0.jar` (+2 to keep from @evlist and another user below)
- [x] castor
  - used by `BeanGenerator`, `ScopeGenerator` and `XXFormsGetScopeAttribute`
- [x] poi
  - 2016-12-06: only used by `XLSUtils` which we can remove (#2822)
- [x] pdfbox (removed in 2016.1)
- [x] `rhino-1.7R2.jar` (unclear why it is needed, but Java 8 has a better JavaScript engine)
  - was used for CoffeeScript task (I think)
  - was also used for experimental server-side JavaScript API
  - 2016-12-06: noting that this got removed for 2016.3
- [x] jaxen and saxpath (see  #2164 and  #2165)
  - 2016-12-06: noting that we can now remove them

**Comment by ebruchez** [comment]
Another [+1 from user](http://discuss.orbeon.com/Announcing-Orbeon-Forms-2016-1-td4661428.html) for keeping XSL-FO. So we should consider creating a module for it.

**Comment by hoila** [comment]
Has fop-1.0 has to be upgraded to fop 2.2 ? 
[fop security](https://xmlgraphics.apache.org/security.html)

```
 Apache™
 FOP Project - Apache FOP Security
 Fixed in FOP 2.2
 medium: XXE vulnerability CVE-2017-5661
 Issue Public: 2017-04-18
 Update Released: 2017-04-10 (FOP 2.2)
 Affects: 2.1 and earlier
```

**Comment by ebruchez** [comment]
We are going to remove FOP entirely from the distribution for Orbeon Forms 2017.2. Unless you are using FOP, it is not needed to keep the JAR file, and you can actually remove it from `WEB-INF/lib`.

**Comment by ebruchez** [comment]
For eXist removal, see #5063.

**Comment by ebruchez** [comment]
Closing this for now. eXist and XMLDB are covered by #5063.
