### ISSUE TITLE
Remaining tasks following unification of recalculate and revalidate

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1773]
Remaining task from #1650:
- [x] deferred event dispatch (#2644)
- [x] recalculate and revalidate force `rebuild` if needed (#1660)
- [x] refresh forces RRR if needed (#1660)
- [x] check #1568

**Comment by ebruchez** [comment]
As a reminder, we want to enforce that *no event* is ever dispatched *during* the actual recalculate/revalidate operation. So if events need to be dispatched, they need to be dispatched after the combined recalculate/revalidate operation has terminated. As noted in #1650, the events are currently:

- `xxforms-xpath-error`
- `xxforms-binding-error`
- `xxforms-value-changed`

The first one is dispatched by `handleMIPXPathException()`.

The last two are dispatched when calling `DataModel.setValueIfChangedHandleErrors()` so that has to be changed to use `setValueIfChanged()` directly.

In all cases, the idea is to collect the events, and then dispatch them.

**Comment by ebruchez** [comment]
All tasks done in other issues, closing.
