### ISSUE TITLE
RFE: Input/textarea fields with character counter

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2121]
## Feature

- For the Input Field, Text Area, and Formatted Text, form authors can independently, in Form Builder:
    - Set the maximum number of characters end users can enter in the field (`max`)
        - This is done in *Control Settings* / *Validations and Alerts*
        - We will have a new validation type: *Max characters* (new radio button), which when selected, in the *Validation Details* column, shows a text field for the form author to enter `max`
    - Enable a character counter on a field
        - This could be a checkbox in *Control Settings* / *Basic Settings*, maybe under "Options"
- This has the following effects
    - When `max` is set, it is taken into account for the validation: if users enter more than `max` characters, the field is invalid
    - When the `counter` is enabled
        - If `max` is set, end users see the message: *`n` characters, `max-n` characters remaining*
        - If `max` isn't set, end users see a message: *`n` characters*
    - These messages are by default shown above the field, aligned on right hand edge

## Implementation

This impacts the `xf:input`, `xf:textarea`, `fr:tinymce` can have an optional character counter. To do this, need 2 distinct features:

1. ability to specify "max length" validation property (see #2242 for details)
2. UI control with counter

Because more than one control can have counter, creating a single XBL component is not a good solution. Idea:

- new e.g. `fr:character-counter` XBL control
- bound to `[appearance ~= character-counter]` (see [CSS selectors](http://www.w3.org/TR/css3-selectors/#attribute-selectors))
- wraps its bound node control and adds counter logic

Tasks:

- [x] evaluate difficulty of adding `[appearance ~= character-counter]` binding to XBL engine (see also #1936)
- [x] implement `[appearance ~= character-counter]` binding to XBL engine
- [x] allow `xf:input[appearance = "character-counter"]`to have precedence over built-in `xf:input` (#2241)
- [x] evaluate difficulty of writing `fr:character-counter` XBL control
- [x] support `xxf:max-length` in XForms engine (part of #2242)
- [x] write `fr:character-counter` XBL control
- [x] support `xxf:max-length` in Form Builder (part of #2242)
- [x] add UI to FB to add "Character counter" to fields (#2252)
- [x] doc
    - [x] migrate Control Details doc from old wiki
    - [x] switching appearances
    - [x] character counter appearance
- [x] try to use CSS table instead of flexbox

See [customer request](https://basecamp.com/1721271/projects/3641011/todos/150020895).

**Comment by ebruchez** [comment]
## How XBL bindings work right now

- `XFormsAnnotator`
  - when finding `xbl:xbl/xbl:binding`, store uri/localname with `Metadata.storeXBLBinding()`
  - when finding an unknown element, calls `metadata.isXBLBindingCheckAutomaticBindings` with the element's uri and localname
    - might be already known
    - if not, try to find `/xbl/$prefix/$localname/$localname.xbl`
      - if found, store uri/localname with `storeXBLBinding` and update `bindingIncludes`

**Comment by ebruchez** [comment]
Details of XBL bindings part moved to #1936.

**Comment by ebruchez** [comment]
Documented
