### ISSUE TITLE
Document changes to fr:number and common constraints

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2497]
- [x] Form Builder
    - [x] "Is Not Negative" (#2488)
    - [x] "Positive, negative-or-zero, and negative common constraints" (#2490)
    - [x] "Maximum Fractional Digits common constraint" (#2491)
- [x] Number
    - [x] binding to `integer` type
    - [x] iOS keyboard behavior
        - see [blog](http://blog.orbeon.com/2016/01/better-numeric-input-on-mobile.html)
        - explain exact cases that show keyboard, including use of `fraction-digits` and `non-negative`
    - [x] explain diff between validation and formatting
- [x] XForms
    - [x] `xxf:non-negative()` and related, `xxf:fraction-digits()`
    - [x] link to these functions from `fr:number` doc

**Comment by ebruchez** [comment]
Form Builder: new common constraints documented (to document [here](http://doc.orbeon.com/form-builder/validation.html#common-constraints).
