### ISSUE TITLE
Unify edit/view pages

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2999]
A number of existing issues are caused by the fact that the `edit` and `view` modes show two different pages, and navigating between the two loses state:

- New → Review → Edit → Save: URL remains at /new #2210
- Liferay: orbeon-liferay-language lost between edit/view/edit #1628
- Review page can be closed by user without warning #1505
- Ask users if they want to load the autosaved data when going from View to Edit #2266

We also have a [+1 from customer](https://basecamp.com/1721271/projects/11908529/messages/63963684) for keeping the state of a custom instance.

What could we do to fix this? Currently, changing mode causes an internal HTTP POST via the `tryChangeMode` function. We pass `form-version` and `data-format-version`. We also pass `fr-noscript`, `fr-language` and `orbeon-embeddable` as needed.

The reason we do a POST is that in effect, the `view` mode is exactly the same form as the `edit` mode, but with "static readonly" controls and the instance marked as readonly.

Now say we do not use an internal POST to change mode: what is the alternative? Staying with the same XForms document, and:

- [ ] change the mode internally
    - [ ] this will cause the instance to no longer be readonly
    - [ ] allow `readonly-appearance` to change dynamically (it is only used by the handlers)
- [ ] update the URL in the browser (history API as we do from `new` to `edit`)
- [ ] send to the client a full update for the content of `fr-form-group`
    - [ ] this must properly deal with JavaScript controls as we do in general with  full updates
- [ ] handle browser back/forward on the client by switching the mode as needed

Can we see any drawback to this besides the implementation effort?

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/311339942) as this creates unnecessary calls to services, in particular for the autocomplete control.

**Comment by ebruchez** [comment]
There is also the question of data permissions:

- load form in edit
    - data permissions are obtained and stored in state
- change mode to view
- data permissions are not preserved, and instead we use `CheckWithoutDataUserPessimistic()` (as of 2023-04)

This particular issue can be solved by securely forwarding data permissions between mode changes.

- [x] handle data permissions
    - this was done with #5437 for Orbeon Forms 2023.1

**Comment by ebruchez** [comment]
We probably won't do this, as:

- edit/view can be significantly different
- they can also run different services in different situations
- we have a better solution to pass state from one mode to another now

So closing.
