### ISSUE TITLE
File Scan API v2

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4967]
We've had a few requests to enhance the API, including:

- File scan API: ability to propagate a specific error message #4960
- File scan API: allow replacement of the file binary #4962
- File scan API: ability to mark the control as invalid if the scan failed #4294
- Pass the filename to the API
- User feedback during file scan #4963

One question is how do we version the API. We don't want to require existing implementations to be rewritten. So we need to create a v2 API. Details TBD.

**Comment by ebruchez** [comment]
Some questions of API design:

1. Can we just extend the current API or do we need  a new API (new Java interfaces/classes)?

2.If we do a separate API, what is the best way to represent failure and success return values?

For 1, so far we have concluded that since we want to add to the return types of `bytesReceived()` and `complete()` methods, which are currently just a plain Java enumeration type, and that we need to enrich that, and that the interface is implemented by the provider, we can't use the existing interface. So we'll create new versions of these interfaces.

For 2, `bytesReceived()` and `complete()` will now return richer information.

Internally, when we got a `REJECT`, we would throw a `FileScanException`. We might want to reconsider this and pass an ADT, `Try`, and/or `Either` up the stack. We have the following conditions:

1. service API throws an exception
    - consider this an `ERROR`
2. service API returns a `REJECT` or `ERROR`
    - can have a custom error message and that's all
    - right now we only distinguish between the two to produce a different error message
3. service API returns a `ALLOW`
    - can have all the other information: custom error message, metadata, and content

**Comment by ebruchez** [comment]
We were going with the following Java API:

```scala
abstract class FileScanResponse {

  def status: FileScanStatus

  def mediatype: ju.Optional[String]              = ju.Optional.empty()
  def filename : ju.Optional[String]              = ju.Optional.empty()
  def content  : ju.Optional[java.io.InputStream] = ju.Optional.empty()
  def message  : ju.Optional[String]              = ju.Optional.empty()
  def extension: ju.Optional[ju.Map[String, Any]] = ju.Optional.empty()
}
```

Now one issue with this is that a service implementor is not constrained in the extra parameter they can provide. For example our description in the previous comment is clear that with a `REJECT` or `ERROR`, it's not possible to provide custom content for example. But the API doesn't enforce that.

In Scala, we can create an ADT, for example:

```scala
sealed trait FileScanResult {
  val message: Option[String]
}

case class FileScanAcceptResult(
  message    : Option[String],
  mediatype  : Option[String]              = None,
  filename   : Option[String]              = None,
  content    : Option[java.io.InputStream] = None,
  extension  : Option[ju.Map[String, Any]] = None
) extends FileScanResult

case class FileScanRejectResult(
  message    : Option[String]
) extends FileScanResult

case class FileScanErrorResult(
  message   : Option[String],
  throwable : Option[Throwable]
) extends FileScanResult
```

Can we, and/or should we, do something similar for Java? One issue is that in Java we can't expressed that the hierarchy is sealed. So what to do if we get a plain `FileScanResult` that is not one of the 3 subtypes?

**Comment by avernet** [comment]
> One issue is that in Java we can't expressed that the hierarchy is sealed.

Could this be a way to do it?
https://garciat.com/posts/java-adt#sum-types

**Comment by ebruchez** [comment]
- [x] design new API
- [x] call new API
- [x] upon `ACCEPT`, propagate message, mediatype, filename, content as `xxforms-upload-done` server event
- [x] upon `REJECT`/`ERROR`, propagate custom message as `xxforms-upload-error` server event
- [ ] handle server events in Form Runner to display custom error message
- [ ] write demo provider
- [ ] manual tests
- [ ] any automated tests?
- [ ] doc

**Comment by ebruchez** [comment]
Regarding the item "don't call `abort()` after `complete()` on provider": both `abort()` and `complete()` are only called by `fileItemState()`. This in turn is called in two places in `processSingleStreamItem()`:

- in the `try` block, creating a `Completed` instance which will cause `complete()` to be called
- in the `catch` block, creating an `Interrupted` instance which will cause `abort()` to be called

Simplified code:

```scala
try {
  ...
  lifecycleOpt flatMap (_.fileItemState(UploadState.Completed(fileItem))) match {
    case ...     =>
    case Some(r) => throw FileScanException(fieldName, r) // to the `catch` at the bottom
  }
} catch {
  case NonFatal(t) =>
    lifecycleOpt foreach (_.fileItemState(UploadState.Interrupted(...))
    throw t
}
```

The question is: is it possible that we call `complete()`, and then `abort()` for the same item? Logically, this is possible if `fileItemState()` crashes, or if `fileItemState()` returns `Some(r)` where `r` is not an `FileScanAcceptResult`.

For the first case, in `fileItemState()`, if `complete()` fails we wrap it in a `Failure`, and if it succeeds we call `fileScanResultFromJavaApi()`, which is very unlikely to fail, looking at the code. So this is very likely not to happen (depending on the correctness of our code!).

However, for the `Some(r)` case that follows, we throw a `FileScanException` which takes us to the `catch` block, which definitely can cause `abort()` to be called.
